services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - redis
      - temporal

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  temporal:
    image: temporalio/auto-setup:1.22.0
    ports:
      - "7233:7233"
      - "8233:8233"
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=${SUPABASE_DB_USER}
      - POSTGRES_PWD=${SUPABASE_DB_PASSWORD}
      - POSTGRES_SEEDS=${SUPABASE_DB_HOST}
      - POSTGRES_TLS_ENABLED=true
      - POSTGRES_TLS=require
      - POSTGRES_DB=${SUPABASE_DB_NAME}
      - SKIP_SCHEMA_SETUP=false

  temporal-ui:
    image: temporalio/ui:2.21.0
    ports:
      - "8080:8080"
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
    depends_on:
      - temporal
    volumes:
        - ./temporal/config:/etc/temporal/config

  # worker:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   command: python -m temporal.worker
  #   depends_on:
  #     - temporal
  #   environment:
  #     - TEMPORAL_ADDRESS=temporal:7233

volumes:
  redis_data:
